name: studyshare_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: 4.0.0
  provider: ^6.1.5
  http: ^1.5.0
  file_picker: ^10.3.3
  shared_preferences: ^2.5.3
  open_file: ^3.5.10



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  